version: "2"
services:
  app:
    container_name: app
    volumes:
      - .:/app
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    command: nodemon --watch server.js --watch views -e js,html --watch routes -e js -L

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
